### ISSUE TITLE
Improvements on SearchMessage.js

### ISSUE THREAD

**Issue by honey-grapes** [RocketChat/EmbeddedChat#148]
While looking through issue #132 I found some things in SearchMessage.js that could be improved upon. Please let me know if you agree and I can start working on them:
- [ ] e.keyCode = 13 is deprecated according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). 
- [ ] There are a couple of inline functions which is usually not great for performance
For the inline functions, please let me know if I should change them for the other ones I see in other files?

Thanks!

**Comment by VenomFate-619** [comment]
many functions are written in JSX directly, they should be outside.
![image](https://user-images.githubusercontent.com/67755128/222918618-1469f8e9-8a2d-4485-b4e5-a90c8a6a9a4e.png)
![image](https://user-images.githubusercontent.com/67755128/222918633-c9eee3a9-06bc-476d-b2f8-75ec3105f621.png)

source:- ChatInput.js

The function inside onChange and onKeyDown should be outside, so that code remains clean
@sidmohanty11

**Comment by sidmohanty11** [comment]
@honey-grapes @VenomFate-619 Yup! These improvements will be huge for improving our code quality! Thanks!

**Comment by VenomFate-619** [comment]
@honey-grapes may be can collbrate on it to make code clean.
If possible we can develop a docs regarding the coding standard and practices.

**Comment by raazseth** [comment]
Can I work on this issue? Please assign me @sidmohanty11

**Comment by umangutkarsh** [comment]
Hi @sidmohanty11 , if this issue has not been resolved, please assign this to me.

**Comment by umangutkarsh** [comment]
Hi @sidmohanty11 , I've created a pull request for the improvements in `SearchMesage.js`. Please provide your feedback if I should proceed with the changes in the inline functions in other files.
