### ISSUE TITLE
Development on Windows

### ISSUE THREAD

**Issue by goran-paunovic** [RocketChat/EmbeddedChat#213]
### Description:

I use Win10. I started my RocketChat server instance and it is running on localhost:3000.
Then I created .env file and set up environment variables.
Tried to start playground using the steps described in readme but when I try to run it nothing happens.

### Expected behavior:

I expect to see something when I go to localhost:4000.

### Actual behavior:

Nothing to be seen.

**Comment by goran-paunovic** [comment]
Same thing happens when using gitpod. 
I can't even install dependencies.
Can somebody tell if this project is maintained by anyone?

**Comment by sidmohanty11** [comment]
Hey @goran-paunovic ! Thanks for using EmbeddedChat and raising this issue!

As of now, EmbeddedChat is breaking due to dependencies mismatch in packages due to which the build is failing. If you want a workaround and want to try this, please do -

```
npm i --legacy-peer
cd playground
npm i
cd ..
npm run dev
```
This should install the dependencies and the build should work.

We have a GSoC (Google Summer of Code) project this year for enhancing EmbeddedChat and taking it to the next level.

Please feel free to stay in touch with me ( @sidmohanty11 ) and ( @abhinavkrin ) who will also be maintaining this project moving on. Also, please join #embeddedchat channel on Rocket.Chat to stay updated. Thanks!!

**Comment by goran-paunovic** [comment]
No luck. I can't get it to work on Windows.
![image](https://github.com/RocketChat/EmbeddedChat/assets/8568410/0d75017c-5f60-4a04-8dac-a2bfc0dca136)

**Comment by sidmohanty11** [comment]
Hey, @goran-paunovic yes actually the dev environment works well in linux-based terminals (bash, zsh etc).

- Can you please try Gitpod, it should be rather easy to setup.
- Else, I can see that you're using PowerShell, can you try this - https://stackoverflow.com/questions/53256555/not-able-to-set-process-env-port-variable-in-windows-for-node ? You can see in the logs that the playground shut down with code 0, which means it didn't get started correctly. I think `set PORT` isn't working as expected. 

Please try the above solution and let me know if it works.

Thanks!

**Comment by goran-paunovic** [comment]
I will leave it here just in case someone else needs it.
To make everything work on Windows, go to `/playground ` folder and change the start command to
`set PORT=4000 && node ../node_modules/react-scripts/bin/react-scripts.js start`
