### ISSUE TITLE
Misplaced position of message toolbox.

### ISSUE THREAD

**Issue by Yashraj7890** [RocketChat/EmbeddedChat#375]
### Description:
The message toolbox appears over the text in case of long text messages.

### Expected behavior:
![Screenshot (46)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/e30f43f7-c4f3-49b8-ab27-14bbeaa8f915)

### Actual behavior:
![Screenshot (45)](https://github.com/RocketChat/EmbeddedChat/assets/98230836/d55e69d9-5720-458a-98e5-84528c63138c)

**Comment by Akshun-01** [comment]
Hey @Yashraj7890 , I think its the padding that is very different and also the defining border of the message box.
What do you think the problem might be?

**Comment by Akshun-01** [comment]
Also while testing this issue, I found another potential issue.
When then text is too long to send, rocketChat gives proper Error message to shorten it or to send it as an attachment.
Whereas, in embedded chats we are logged out.

[Screencast from 01-02-2024 05:52:29 PM.webm](https://github.com/RocketChat/EmbeddedChat/assets/93793691/ac764715-09d6-45db-a8b0-ec37ffb6e9ec)

I think we should handle this error properly and give a message rather than logging out the user?

**Comment by Yashraj7890** [comment]
> Also while testing this issue, I found another potential issue. When then text is too long to send, rocketChat gives proper Error message to shorten it or to send it as an attachment. Whereas, in embedded chats we are logged out.
> 
>  Screencast.from.01-02-2024.05.52.29.PM.webm 
> I think we should handle this error properly and give a message rather than logging out the user?

feel free to raise a separate issue for this and it will be reviewed there and you can start working on it
