### ISSUE TITLE
Refactor menu components

### ISSUE THREAD

**Issue by JeffreytheCoder** [RocketChat/EmbeddedChat#504]
As an EmbeddedChat developer

**I need to**:
Refactor the menu components.

Currently, each menu below has an individual store, component, and css module:
1. Room information
2. Members
4. Threads
5. Search
6. Mentions
7. Pinned messages
8. Starred messages

Most of the code are repeated and can be refactored into a general menu framework. 

**So That**:
We...
1. Improve UI consistency
2. Enhance maintainability of existing menus
3. Bring easier enhancement with future menu features and better scalability with new menus

**Acceptance Criteria**

- [ ] All current menus share a general component, CSS module, and store.
- [ ] The menus behave the same as before
- [ ] The refactored menu framework have flexibility for all types of menus

**Comment by JeffreytheCoder** [comment]
Working on this...might take a while

**Comment by Spiral-Memory** [comment]
Great issue! 🚀 Just change things with caution while handling it. There's a potential for a breaking change if not approached carefully. Wishing you all the best!

**Comment by Spiral-Memory** [comment]
I suggest keeping the stores separate due to numerous dependencies. Even after refactoring, each individual component should remain. Focus on extracting common CSS modules and the shared sidebar component along with its logic. Other sidebars can then implement and modify this common shared component.
