### ISSUE TITLE
EmbeddedChat npm package cannot be accessed 

### ISSUE THREAD

**Issue by Alenjojo** [RocketChat/EmbeddedChat#52]
### Description:
When i try to install the package from npm it says not found.
Then if i try to install and use it manually, error pops up and doesn't work

### Steps to reproduce:

1. install from `npm i @rocket.chat/embeddedchat`
2. We can see the npm errors
3. Install directly from github still throws error

### Expected behavior:
It should get install normally without a hassle 

### Actual behavior:
As it is not registered with npm cannot download it, neither the manual install works

**Comment by sidmohanty11** [comment]
Hey @Alenjojo , thanks for the interest in using EmbeddedChat. We are super thrilled to get your feedback on the product. EmbeddedChat currently is not officially published in npm registry though we are planning to do that quite soon (expected in 1-2 weeks). I believe you could try it now by doing,

```
npm i github:RocketChat/EmbeddedChat
```

and follow this repository as an example -> https://github.com/sidmohanty11/embeddedchat-demo-deploy

Thanks,

Please let me know if you face any issues

**Comment by Alenjojo** [comment]
@sidmohanty11  hey, thanking for getting back. Well i even tried it installing it manually and still im facing some npm errors. It won't install until i  force it to and still it causes exceptions.
![Screenshot 2022-10-26 105353](https://user-images.githubusercontent.com/51394913/197942191-a2327516-0cb0-4f69-b444-7a1427366f65.png)

I guess it supports previous version of node, but it wasn't mentioned in the Readme

Node ver - 18.12.0
react.js ver -18.2.0

**Comment by Alenjojo** [comment]
Btw i tried to clone and run your repo, well it worked.
But still it wasn't possible for me to install on my project

**Comment by sidmohanty11** [comment]
Hey @Alenjojo , thanks for pointing this out. I think it's erroring out due to the exact versioning of react v17 only in package.json under peerDeps:

https://github.com/RocketChat/EmbeddedChat/blob/9f094a9553cfb7c6eb9dcdb69db34bc876392c6e/package.json#L35

Would you like to contribute to the project? It will be a simple fix I think. We can just update `react` and `react-dom` to `^17.0.2 || ^18`

Take a look over this issue's fix: https://github.com/auth0/react-native-auth0/issues/495 and let me know if you wish to move forward or if it works.

Again, thanks

**Comment by Alenjojo** [comment]
sure, i'd love to thanks
absolutely

**Comment by Alenjojo** [comment]
@sidmohanty11  hey, I've done that and checked it, it installs flawlessly
created a PR for that
Thanks

**Comment by gadosteamhub** [comment]
is there a package for this? i cannot install it anymore
