### ISSUE TITLE
Bug: Error Pinning the Message

### ISSUE THREAD

**Issue by yours-majesty** [RocketChat/EmbeddedChat#639]
### Description:

When I am clicking on Pin icon to pin my message it's showing an error.Its showing error pinning the message.Look at the video that I had shared for more consice info.

### Expected behavior:

The expected behaviour should be my messages will got pinned on clicking on the pin icon

### Actual behavior:

But it's actually returning an error.

https://github.com/user-attachments/assets/77e1c2fa-7081-418e-9174-0ce5d9b5169d

**Comment by devanshkansagra** [comment]
Hey @yours-majesty, there is no point of raising this issue, the pinning and unpinning of messages is handled by admin of Rocket chat server so non-admin users cannot pin-unpin the messages.

### My admin Login in my RocketChat Server:
![image](https://github.com/user-attachments/assets/d2cbc576-10db-4452-9ae4-a2795ab1e91b)

### My Non admin login in my RocketChat server
![image](https://github.com/user-attachments/assets/c8c6b241-4310-42a7-979a-9ab12061204a)

If you look closely there is an option of pin in the admin part and it is not there in non-admin part.

These are my observations till now

@Spiral-Memory and other maintainers of this project Please share yours also so that I can get to know whether I am correct or not

**Comment by Spiral-Memory** [comment]
@yours-majesty 
@devanshkansagra 

Refer to this issue : https://github.com/RocketChat/EmbeddedChat/issues/519

**Comment by devanshkansagra** [comment]
Yea @Spiral-Memory That also I observed that there is unwanted visiblity of pin icon on non - admin users side in the EmbeddedChat

**Comment by Spiral-Memory** [comment]
Yeah, One of you or collaboratively work on it if you want or you can review the already raised PR and see if it is fine or modifications are needed

**Comment by devanshkansagra** [comment]
I am reviewing it that pr and @yours-majesty you can also join and start your contribution journey
